export const mockCandles = [
	{
		entity: {
			id: '10',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
	{
		entity: {
			id: '11',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
	{
		entity: {
			id: '10',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
	{
		entity: {
			id: '10',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
	{
		entity: {
			id: '10',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
	{
		entity: {
			id: '10',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
	{
		entity: {
			id: '10',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
	{
		entity: {
			id: '10',
			name: 'Candle',
			description: 'A nice candle',
			price: 23,
			sku: '123',
		},
		image: 'candle.jpg',
		category: 'home',
		subCategory: 'candles',
		tags: ['home', 'candles'],
		rating: 5,
		reviews: 100,
		stock: 1000,
		isOnSale: false,
		saleStart: new Date(),
		saleEnd: new Date(),
		isFeatured: true,
		isTopSeller: true,
		isNew: false,
		isBestSeller: true,
		isSale: false,
		isAvailable: true,
		isOutOfStock: false,
		isComingSoon: false,
		isDiscontinued: false,
		isLimited: false,
		isSoldOut: false,
		isBackOrder: false,
		isPreOrder: false,
		isGift: false,
		subscription: {
			type: 'monthly',
			entity: {
				id: '10',
				name: 'Candle of the Month',
				description: 'A nice candle every month',
				price: 23,
				sku: '123',
			},
			isRecurring: true,
		},
		fragrance: 'lavender',
		color: 'purple',
		size: 'medium',
		burnTime: '10 hours',
		scent: 'lavender',
		brand: 'Candle Co',
		type: 'wax',
		material: 'soy',
		shape: 'round',
		weight: '10 oz',
		dimensions: '4x4x4',
		wickType: 'cotton',
		wickMaterial: 'cotton',
	},
]
