export const candleMock = {
	entity: {
		id: '1',
		name: 'Cedarwood & Vanilla',
		description: 'A warm, woody scent with a hint of sweetness.',
		price: 24.99,
		sku: 'C1',
	},
	buttons: [
		{
			label: 'Add to Cart',
			palleteColor: 'primary',
			disabled: false,
			size: 'medium',
		},
		{
			label: 'Add to Wishlist',
			palleteColor: 'secondary',
			disabled: false,
			size: 'medium',
		},
	],
	brand: 'RFS',
	color: 'Brown',
	material: 'Soy Wax',
	dimensions: '3.5" x 3.5" x 3.5"',
	weight: '12 oz',
	fragrance: 'Cedarwood & Vanilla',
	size: '3.5" x 3.5" x 3.5"',
	burnTime: '60 hours',
	scent: 'Woody, Sweet',
	type: 'Candle',
	shape: 'Cylinder',
	wickType: 'Cotton',
	wickMaterial: 'Cotton',
	category: 'Candles',
	subCategory: 'Candle',
	tags: ['Cedarwood', 'Vanilla', 'Soy Wax', 'Brown', 'Candle'],
	rating: 5,
	reviews: 100,
	stock: 100,
	isOnSale: false,
	saleStart: '',
	saleEnd: '',
	isFeatured: false,
	isTopSeller: false,
	isNew: false,
	isBestSeller: false,
	isSale: false,
	isAvailable: true,
	isOutOfStock: false,
	isComingSoon: false,
	isDiscontinued: false,
	isLimited: false,
	isSoldOut: false,
	isBackOrder: false,
	isPreOrder: false,
	isGift: false,
	image: 'https://i.imgur.com/vL2h90y.jpg',
	subscription: {
		type: 'One-Time Purchase',
		isRecurring: false,
		entity: {
			id: '1',
			name: 'Cedarwood & Vanilla',
			description: 'A warm, woody scent with a hint of sweetness.',
			price: 24.99,
			sku: 'C1',
		},
	},
}
